### PR TITLE
OT-757: Regression: Flagged Messages not filtered per Chat

### LINKED ISSUE #482: Push notifications were sporadically not sent on iOS
**Describe the bug**
Push notifications were sporadically not sent

**To Reproduce**
Occurrence: 5 out of 10 times]
1. User#A: Put the app to background
2. User#B: Send message to User#A

**Expected behavior**
A push notification should appear on mobile of user#A

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.600.0 (513)
 - Plugin version: 
 - Delta Chat Core version:
 - Flutter version:

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4

**Additional context**

### LINKED ISSUE #483: Regression: Flagged Messages not filtered per Chat
### Describe the bug
Regression for #302 - List Flagged Messages per Conversation.
Actually in chats (for both group and single chats)always all flagged messages are shown.

### To Reproduce
Occurrence: _always_

1. Open a group chat, star some messages
2. Open a one-to-one chat, star some messages
3. Tap top navigation bar (chat name) in group or one-to-one chat
4. Select _"Flagged Messages"_
5. All flagged messages are shown (from all chats)

### Expected behavior
Flagged messages should be filtered by current chat.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-757).

### PR DESCRIPTION
**Pull request by phranck**
**Link to the given issue**
Fixes #483, Closes #483 

### Fixes
* adds missing `chatId` parameter when calling `Flagged` widget
* comments some code out (needs to be discussed) for flagged messages per contact

### CODE REVIEW

File: lib/src/contact/contact_details.dart [hunk 1]
```diff
@@ -142,12 +142,13 @@ class _ContactDetailsState extends State<ContactDetails> with ChatCreateMixin {
...
-                    iconBackground: CustomTheme.of(context).flagIcon,
-                    onTap: () => _settingsItemTapped(context, SettingsItemName.flagged),
-                  ),
+//TODO: This should be discussed (Flagged messages per user)!
+//                  SettingsItem(
+//                    icon: IconSource.flag,
+//                    text: L10n.get(L.settingItemFlaggedTitle),
+//                    iconBackground: CustomTheme.of(context).flagIcon,
+//                    onTap: () => _settingsItemTapped(context, SettingsItemName.flagged),
+//                  ),
```
Comment (florianhaar) [inline lib/src/contact/contact_details.dart]: Was it a request from the design team? If not, we should discuss this now before we merge it. Just my thoughts :)

Comment (florianhaar) [reply lib/src/contact/contact_details.dart]: The designs say that a contact profile has a flagged messages item.

Comment (phranck) [reply lib/src/contact/contact_details.dart]: The decision to take it out for the moment was lined up with @Boehrsi yesterday.

Comment (florianhaar) [reply lib/src/contact/contact_details.dart]: Alright
