### PR TITLE
OT-745: Unable To Play Received Videos

### LINKED ISSUE #476: Unable to play received videos
**Describe the bug**
I'm unable to play received videos. Neither in COI app nor in any other iOS app. The selected file will be compressed and the compressed file renamed to

Trim.F08B7DA0-68D4-4D7C-88C9-A2898C146A7.MOV

before sending.

The received file can only be stored local to be played in an other app. The local stored file will also be renamed.

New file name: video.c88619fa-8b01-4a83-8359-6228d952

None of my video apps are able to play this video.

**To Reproduce**
Occurrence: always
1. Go to "Chat"
2. Open a chat
3. Hit the "+" button
4. Choose "Video"
5. Select a video
6. Send the video
7. store the received video local and try to play

**Expected behavior**
The video should be stored as known file and playable with any video app.

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.600.0 (513)
 - Plugin version:
 - Delta Chat Core version:
 - Flutter version:

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4 final

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-745).

### PR DESCRIPTION
**Pull request by phranck**
### Link to the given issue
Fixes #476 - Unable to play received videos

### Solution
* updates `file_picker` plugin to latest version
* implements a dirty hack, so that the Core can handle video as expected

### CODE REVIEW

File: lib/src/chat/chat.dart [hunk 1]
```diff
@@ -827,10 +827,22 @@ class _ChatState extends State<Chat> with ChatComposer, ChatCreateMixin, InviteM
...
     String filePath = await FilePicker.getFilePath(type: fileType, fileExtension: extension);
     if (filePath == null) {
       return;
     }
+
+    if (fileType == FileType.video) {
+      final ext = Path.extension(filePath);
+      final videoFileName = "${filePath.hashCode}$ext";
+      final videoFileDir = Path.dirname(filePath);
+      final videoFilePath = "$videoFileDir/$videoFileName";
```
Comment (Boehrsi) [inline lib/src/chat/chat.dart:840]: Looks all good, just one thing, let's use https://api.dart.dev/stable/2.7.2/dart-io/Platform/pathSeparator.html instead of "/" to concatenate paths..

**Comment by Boehrsi** [comment]
Review done, now testing functionally on Android.

File: lib/src/chat/chat.dart (hunk 1 above)
Comment (phranck) [reply lib/src/chat/chat.dart:840]: Great advice, didn't know that!

Comment (phranck) [reply lib/src/chat/chat.dart]: @Boehrsi Changes done.
