### PR TITLE
OT-717: Unreadable Status Bar

### LINKED ISSUE #449: Unreadable status bar if dark mode is enabled
**Describe the bug**

The status bar is unreadable if dark mode is enabled. This happens due to the black background color and the black text color.

**Additional context**

This happens only on iOS.

### PR DESCRIPTION
**Pull request by phranck**
Fixes #449

BUGFIX
* Fixes a bug that happens on switching between Light and Dark mode, which results in an unreadable system status bar

ADDITIONS & CHANGES
* Adds a new `ThemeKey` enum value `system`
* Changes setting for Light/Dark mode in user profile by removing the switch
* Adds a new screen for switching application appearance to `Light`/`Dark` or `System`
* Refactors all `ThemeKey` enum values from UPPERCASE to lowercase
* Adds `vibrateLight` method for haptic feedback when user changes appearance
* Adds new assets for all three theme states: Light, Dark, System
* Adds method extension with a getter `stringValue` for `enum ThemeKey` to get a string of the enum value only
* Cleans up code

ADDITIONAL NOTES
* Adds `activeColor` setting to all used `Switch.adaptive` widgets with the value of `CustomTheme.of(context).accent`, because on iOS they had the default green color which doesn't fit our application color theme (unrelated regarding the topic of the ticket).

---
*Removed after first discussion*
* ~Adds `Preference` class with just two static methods `set({@required value, @required String forKey})` and `value({@required String forKey})` for convenience and better readability~
* ~Adds static getter/setter on `Preference` class for easier handling of preference values and better readability (**NOTE: Should be discussed if we adopt this system overall**)
  So instead of calling:~
  ```
  setPreference(preferenceAppThemeKey, describeEnum(ThemeKey.light));
  ```
  we can call:
  ```
  Preference.themeKey = ThemeKey.light.stringValue;
  ```

### CODE REVIEW

File: lib/src/brandable/custom_theme.dart [hunk 1]
```diff
@@ -140,6 +145,24 @@ class CustomTheme extends StatefulWidget {
...
+      return ThemeKey.dark;
+    }
+  }
+
+  static ThemeKey get systemThemeKey {
+    final brightness = WidgetsBinding.instance.window.platformBrightness;
+    if (brightness == Brightness.light) {
+      return ThemeKey.light;
+    }
+    return ThemeKey.dark;
```
Comment (florianhaar) [inline lib/src/brandable/custom_theme.dart:164]:
```suggestion
   return brightness == Brightness.light ? ThemeKey.light : ThemeKey.dark;
```
This could be shorten :)

Comment (phranck) [reply lib/src/brandable/custom_theme.dart:164]: True!

**Comment by phranck** [comment]
> After setting the appearance to "system" the status bar is completely dark. Light and dark work perfect. See attached image:
> Screenshot_20200407-063454_OX COI Messenger Dev

Oh damn... this is a regression. Thanks!

**Comment by phranck** [comment]
@florianhaar @Boehrsi 
Triggered by [Flutter this issue](https://github.com/flutter/flutter/issues/53034) I tried the Flutter `beta` channel and tested again. Et voilá - it works as expected on both Android and iOS!

**Comment by Boehrsi** [comment]
Notes / stuff to check tomorrow:

- Setting the accent color on numerous elements shouldn't be required as this should normally be handled by the global theme
- Dimensions file: 6dp value should be a specific value not a default
- Check theme logic and compare with system and set something depending on this seems to be quite often in there. Possible to simplify in 1-2 methods?
